<a href="https://colab.research.google.com/github/MB-Icepick/U_ML_BC/blob/main/Test2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install scikit-learn
!pip install --upgrade scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 48.2 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2


In [4]:

import numpy as np
import pandas as pd
import sklearn

sklearn.__version__


'1.5.1'

In [5]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data=data)
df_raw


size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [6]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


In [7]:
for col in ['size', 'color', 'gender', 'bought']:
    df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 740.0 bytes


In [8]:
df.describe()


price      weight
count    5.000000    5.000000
mean   119.000000  408.000000
std     48.476799   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%     99.000000  410.000000
75%    129.000000  450.000000
max    199.000000  500.000000

In [9]:


df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [10]:
df.describe(include=['category']).T

count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

In [11]:

df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [12]:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [13]:
le.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [14]:
le.classes_

array(['no', 'yes'], dtype=object)

In [15]:
df['bought'] = le.fit_transform(df['bought'])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [16]:
le.inverse_transform(df['bought'])

array(['yes', 'no', 'yes', 'no', 'yes'], dtype=object)

In [17]:

df['bought'] = le.inverse_transform(df['bought'])
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [21]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
encoder.fit(df[['size']])

OneHotEncoder()

In [22]:
encoder.transform(df[['size']])

<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [23]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [26]:
encoder = OneHotEncoder(drop='first')
encoder.fit(df[['size']])
encoder.transform(df[['size']])

<5x2 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [25]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [27]:
pd.get_dummies(data=df)


price  weight  size_L  size_M  size_XL  color_blue  color_green  color_red  \
0  199.0   500.0   False   False     True       False        False       True   
1   89.0   450.0    True   False    False       False         True      False   
2   99.0   300.0   False    True    False        True        False      False   
3  129.0   380.0    True   False    False       False         True      False   
4   79.0   410.0   False    True    False       False        False       True   

   gender_female  gender_male  bought_no  bought_yes  
0           True        False      False        True  
1          False         True       True       False  
2          False         True      False        True  
3           True        False       True       False  
4           True        False      False        True

In [28]:
pd.get_dummies(data=df, drop_first=True)

price  weight  size_M  size_XL  color_green  color_red  gender_male  \
0  199.0   500.0   False     True        False       True        False   
1   89.0   450.0   False    False         True      False         True   
2   99.0   300.0    True    False        False      False         True   
3  129.0   380.0   False    False         True      False        False   
4   79.0   410.0    True    False        False       True        False   

   bought_yes  
0        True  
1       False  
2        True  
3       False  
4        True

In [29]:
pd.get_dummies(data=df, drop_first=True, prefix='new')

price  weight  new_M  new_XL  new_green  new_red  new_male  new_yes
0  199.0   500.0  False    True      False     True     False     True
1   89.0   450.0  False   False       True    False      True    False
2   99.0   300.0   True   False      False    False      True     True
3  129.0   380.0  False   False       True    False     False    False
4   79.0   410.0   True   False      False     True     False     True

In [30]:
pd.get_dummies(data=df, drop_first=True, prefix_sep='-')

price  weight  size-M  size-XL  color-green  color-red  gender-male  \
0  199.0   500.0   False     True        False       True        False   
1   89.0   450.0   False    False         True      False         True   
2   99.0   300.0    True    False        False      False         True   
3  129.0   380.0   False    False         True      False        False   
4   79.0   410.0    True    False        False       True        False   

   bought-yes  
0        True  
1       False  
2        True  
3       False  
4        True

In [31]:
pd.get_dummies(data=df, drop_first=True, columns=['size'])

color  gender  price  weight bought  size_M  size_XL
0    red  female  199.0   500.0    yes   False     True
1  green    male   89.0   450.0     no   False    False
2   blue    male   99.0   300.0    yes    True    False
3  green  female  129.0   380.0     no   False    False
4    red  female   79.0   410.0    yes    True    False

In [32]:
print(f"{df['price']}\n")
print(f"Średnia: {df['price'].mean()}")
print(f"Odchylenie standardowe: {df['price'].std():.4f}")


0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

Średnia: 119.0
Odchylenie standardowe: 48.4768


In [33]:
(df['price'] - df['price'].mean()) / df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [34]:
def standardize(x):
    return (x - x.mean()) / x.std()

standardize(df['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [35]:

from sklearn.preprocessing import scale

scale(df['price'])

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df[['price']])
scaler.transform(df[['price']])

array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [37]:
scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])
df

size  color  gender     price    weight bought
0   XL    red  female  1.845062  1.366002    yes
1    L  green    male -0.691898  0.623610     no
2    M   blue    male -0.461266 -1.603567    yes
3    L  green  female  0.230633 -0.415740     no
4    M    red  female -0.922531  0.029696    yes

In [38]:
df = df_raw.copy()
df


size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [39]:
le = LabelEncoder()

df['bought'] = le.fit_transform(df['bought'])

scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])

df = pd.get_dummies(data=df, drop_first=True)
df

price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1   False     True        False       True   
1 -0.691898  0.623610       0   False    False         True      False   
2 -0.461266 -1.603567       1    True    False        False      False   
3  0.230633 -0.415740       0   False    False         True      False   
4 -0.922531  0.029696       1    True    False        False       True   

   gender_male  
0        False  
1         True  
2         True  
3        False  
4        False

In [47]:

data = {
    'size': ['XL', 'L', 'M', np.nan, 'M', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red', 'green'],
    'gender': ['female', 'male', np.nan, 'female', 'female', 'male'],
    'price': [199.0, 89.0, np.nan, 129.0, 79.0, 89.0],
    'weight': [500, 450, 300, np.nan, 410, np.nan],
    'bought': ['yes', 'no', 'yes', 'no', 'yes', 'no']
}

df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

In [48]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   6 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  4 non-null      float64
 5   bought  6 non-null      object 
dtypes: float64(2), object(4)
memory usage: 416.0+ bytes


In [49]:
df.isnull()

size  color  gender  price  weight  bought
0  False  False   False  False   False   False
1  False  False   False  False   False   False
2  False  False    True   True   False   False
3   True  False   False  False    True   False
4  False  False   False  False   False   False
5  False  False   False  False    True   False

In [50]:
df.isnull().sum()

size      1
color     0
gender    1
price     1
weight    2
bought    0
dtype: int64

In [51]:
df.isnull().sum().sum()

5

In [52]:
df.isnull().sum()/len(df)

size      0.166667
color     0.000000
gender    0.166667
price     0.166667
weight    0.333333
bought    0.000000
dtype: float64

In [53]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(df[['weight']])

SimpleImputer()

In [55]:
imputer.statistics_

array([415.])

In [56]:
imputer.transform(df[['weight']])

array([[500.],
       [450.],
       [300.],
       [415.],
       [410.],
       [415.]])

In [57]:
df['weight']=imputer.transform(df[['weight']])
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0   415.0     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0   415.0     no

In [59]:
imputer = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=99.0)
imputer.fit_transform(df[['price']])

array([[199.],
       [ 89.],
       [ 99.],
       [129.],
       [ 79.],
       [ 89.]])